#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1595132894                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Access your local files and folders on the web.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.
footer                                    : Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>



# Information About Yourself
your_name                                 : 
your_link                                 : 
your_city                                 : 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : File System Access API
    description                           : This extension adds iOS support for <a href="https://web.dev/file-system-access/">new web APIs</a> that allow websites and webapps to access local files and folders.
    icon                                  : globe
    
  - title                                 : Run rich web apps on iOS
    description                           : Use <a href="https://vscode.dev">vscode.dev</a> to write code from your iPad or <a href="https://photopea.com">Photopea</a> to edit images. This extension works on any website that supports File System Access APIs.
    icon                                  : apps

  - title                                 : Built in security
    description                           : iOS has a built in file system sandbox that File Picker participates in. That means no website can access any data you do not explicitly grant permission to open.
    icon                                  : lock

  - title                                 : Supports streaming APIs
    description                           : Legacy file access must preload the entire file in memory. Websites that use the new APIs along with File Picker extension can read files in chunks at arbitary offsets, saving memory and improving performance.
    icon                                  : pipe

  - title                                 : Atomic writes
    description                           : As per the API specification, writes are only saved when the file is closed by the website. That means you will not lose data if your connection is lost while a file is opened.
    icon                                  : atom
  
  - title                                 : Open folders
    description                           : Supported websites can open local folders for reading and writing existing files as well as create new files.
    icon                                  : folder



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                                           # Replace with alternative image path or image URL.
cover_overlay_color                       : "#258EA6"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

include:
  - .well-known

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
